#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: ConfigMap
apiVersion: "1.0"
metadata:
  name: arana-config
data:
  tenants:
    - name: arana
      users:
        - username: root
          password: "123456"
        - username: arana
          password: "123456"
      clusters:
        - name: employees
          type: mysql
          sql_max_limit: -1
          tenant: arana
          groups:
            - name: employees_0000
              nodes:
                - node0
      sharding_rule:
        tables:
          - name: employees.student
            allow_full_scan: true
            sequence:
              type: snowflake
              option:
            db_rules:
              - column: uid
                type: scriptExpr
                expr: parseInt(0)
            tbl_rules:
              - column: uid
                type: scriptExpr
                expr: $value % 32
            topology:
              db_pattern: employees_0000
              tbl_pattern: student_${0000..0031}
            attributes:
              sqlMaxLimit: -1
      nodes:
        node0:
          name: node0
          host: arana-mysql
          port: 3306
          username: root
          password: "123456"
          database: employees_0000
          weight: r10w10
