listeners:
  - protocol_type: mysql
    socket_address:
      address: 0.0.0.0
      port: 13306
    config:
      users:
        dksl: "123456"
      server_version: 5.7.0
    executor: redirect

executors:
  - name: redirect
    mode: singledb
    data_sources:
      - master: employees

data_source_cluster:
  - role: master
    type: mysql
    name: employees
    capacity: 10
    max_capacity: 20
    idle_timeout: 60s
    conf:
      dsn: root:123456@tcp(arana-mysql:3306)/employees?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8